// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.kew.rmf.matchconf;

import javax.persistence.Entity;

privileged aspect Wire_Roo_Jpa_Entity {
    
    declare @type: Wire: @Entity;
    
}
