// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.kew.shs.dedupl.matchconf;

import org.kew.shs.dedupl.matchconf.Configuration;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Configuration_Roo_Configurable {
    
    declare @type: Configuration: @Configurable;
    
}
