// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.kew.stringmod.matchconf;

import javax.persistence.Entity;
import org.kew.stringmod.matchconf.Transformer;

privileged aspect Transformer_Roo_Jpa_Entity {
    
    declare @type: Transformer: @Entity;
    
}
