// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.kew.stringmod.matchconf;

import org.kew.stringmod.matchconf.WiredTransformer;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect WiredTransformer_Roo_Configurable {
    
    declare @type: WiredTransformer: @Configurable;
    
}
